import * as Yup from "yup";

export const checkout = {
  formId: "create-customer-form",
  formField: {
    first_name: {
      name: "first_name",
      label: "first name",
      type: "text",
      placeholder: "eg. Ali",
      errorMsg: "First name is required.",
    },
    last_name: {
      name: "last_name",
      label: "last name",
      type: "text",
      placeholder: "eg. Jawish",
      errorMsg: "Last name is required.",
    },
    position: {
      name: "position",
      label: "position",
      type: "text",
      placeholder: "eg. CTO",
      errorMsg: "Position is required."
    },
    email: {
      name: "email",
      label: "email",
      type: "text",
      placeholder: "eg. admin@tnafos.com",
      errorMsg: "Email address is required.",
      invalidMsg: "Your email address is invalid",
    },
    phone_number: {
      name: "phone_number",
      label: "Phone number",
      type: "text",
      placeholder: "eg. 507820331",
      errorMsg: "Phone number is required."
    },
    company_name: {
      name: "company_name",
      label: "Company name",
      type: "text",
      placeholder: "eg. Tnafos",
      errorMsg: "Company name is required.",
    },
    fax: {
      name: "fax",
      label: "Fax number",
      type: "number",
      placeholder: "eg. 0114973737",
      errorMsg: "Fax is required.",
    },
    website: {
      name: "website",
      label: "Website",
      type: "text",
      placeholder: "eg. https://tnafos.com",
      errorMsg: "Website is required.",
    },
    currency: {
      name: "currency",
      label: "currency",
      type: "text",
      placeholder: "eg. SAR",
      errorMsg: "currency is required.",
    },
    language: {
      name: "language",
      label: "Language",
      type: "text",
      placeholder: "eg. AR",
      errorMsg: "language is required.",
    },
    status: {
      name: "status",
      label: "Status",
      type: "text",
      placeholder: "eg. SAR",
      errorMsg: "Status is required.",
    },
    country_id: {
      name: "country_id",
      label: "Country",
      type: "text",
      placeholder: "eg. saudi arabia",
      errorMsg: "Country is required.",
    },
    address: {
      name: "address",
      label: "Address",
      type: "text",
      placeholder: "eg. address",
      errorMsg: "Address is required.",
    },
    city: {
      name: "city",
      label: "City",
      type: "text",
      placeholder: "eg. Riyadh",
      errorMsg: "City is required.",
    },
    state: {
      name: "state",
      label: "State",
      type: "text",
      placeholder: "eg. Riyadh",
      errorMsg: "State is required.",
    },
    zipcode: {
      name: "zipcode",
      label: "Zip code",
      type: "text",
      placeholder: "eg. 11223",
      errorMsg: "Zip code is required.",
    },
    assigned_to: {
      name: "assigned_to",
      label: "Assigned to",
      type: "text",
      placeholder: "eg.",
      errorMsg: "Assigned to is required.",
    },
    source_id: {
      name: "source_id",
      label: "Source id",
      type: "text",
      placeholder: "eg.",
      errorMsg: "Source is required.",
    },
    country_code: {
      name: "language",
      label: "language",
      type: "text",
      placeholder: "eg. AR",
      errorMsg: "Language is required.",
    },
  }
};

const {
  formField: {
    first_name,
    last_name,
    position,
    email,
    phone_number,
    company_name,
    fax,
    website,
    currency,
    language,
    status,
    country_id,
    address,
    city,
    state,
    zipcode,
    assigned_to,
    source_id,
    country_code,
  },
} = checkout;


export const initialValue = {
  first_name: "",
  last_name: "",
  position: "",
  email: "",
  phone_number: "",
  company_name: "",
  fax: "",
  website: "",
  currency: "",
  language: "",
  status: false,
  country_id: "",
  address: "",
  city: "",
  state: "",
  zipcode: "",
  assigned_to: "",
  source_id: "",
  country_code: "",
}

export const validation = [
  Yup.object().shape({
    [first_name.name]: Yup.string().required(first_name.errorMsg),
    [last_name.name]: Yup.string().required(last_name.errorMsg),
    [position.name]: Yup.string().required(position.errorMsg),
    [email.name]: Yup.string().required(email.errorMsg).email(email.invalidMsg),
    [phone_number.name]: Yup.string().required(phone_number.errorMsg),
    [company_name.name]: Yup.string().required(company_name.errorMsg),
    [fax.name]: Yup.number().required(fax.errorMsg),
    [website.name]: Yup.string().required(website.errorMsg),
    [currency.name]: Yup.string().required(currency.errorMsg),
    [language.name]: Yup.string().required(language.errorMsg),
    [status.name]: Yup.bool().required(status.errorMsg),
    [address.name]: Yup.string().required(address.errorMsg),
    [city.name]: Yup.string().required(city.errorMsg),
    [state.name]: Yup.string().required(state.errorMsg),
    [zipcode.name]: Yup.number().required(zipcode.errorMsg),
    // [source_id.name]: Yup.string().required(source_id.errorMsg),
    // [assigned_to.name]: Yup.string().required(assigned_to.errorMsg),
    // [country_id.name]: Yup.string().required(country_code.errorMsg),
  }),
];
